# Generated by Django 4.1.3 on 2022-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='speDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('human', 'human'), ('ecoli', 'E. coli'), ('yeast', 'S. cerevisiae')], default='human', max_length=30)),
            ],
        ),
    ]
